# Nama : Diky Dwicandra
# Nim : 2109106038
# Kelas : A2 2021
## POSTTEST 7

### Import Library

In [2]:
import tensorflow as tf
import numpy as np

### Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [3]:
random_tensor = tf.random.normal([5,5], seed = 1)
random_tensor.numpy()

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

### Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [6]:
tensor_x = [1, 2, 3, 4, 5],[11, 12, 13, 14, 15],[21, 22, 23, 24, 25],[31, 32, 33, 34, 35],[41, 42, 43, 44, 45]
prime_tensor= tf.convert_to_tensor(tensor_x, dtype = tf.float32)
print("prime_tensor : ",prime_tensor.numpy())

prime_tensor :  [[ 1.  2.  3.  4.  5.]
 [11. 12. 13. 14. 15.]
 [21. 22. 23. 24. 25.]
 [31. 32. 33. 34. 35.]
 [41. 42. 43. 44. 45.]]


### Tampilkan dimensi dari kedua variable tersebut

In [7]:
random_tensor.shape

TensorShape([5, 5])

In [8]:
prime_tensor.shape

TensorShape([5, 5])

### Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

#### 1. Penjumlahan

In [12]:
print("Penjumlahan : ", tf.add(prime_tensor,random_tensor))

Penjumlahan :  tf.Tensor(
[[ 0.18868178  3.4845986   3.0653293   1.5572958   5.0992484 ]
 [11.591225   12.592823   10.87707    13.277102   14.943729  ]
 [21.643545   21.735676   24.856632   24.567842   24.617165  ]
 [29.514656   33.261772   32.974693   33.73537    36.532814  ]
 [39.257023   41.562107   42.43399    44.32067    46.13283   ]], shape=(5, 5), dtype=float32)


#### 2. Pengurangan

In [14]:
print("Pengurangan : ",tf.subtract(random_tensor, prime_tensor))

Pengurangan :  tf.Tensor(
[[ -1.8113182   -0.51540124  -2.9346707   -6.442704    -4.9007516 ]
 [-10.408775   -11.407177   -15.12293    -14.722898   -15.056271  ]
 [-20.356455   -22.264324   -21.143368   -23.432158   -25.382835  ]
 [-32.485344   -30.73823    -33.025307   -34.26463    -33.467186  ]
 [-42.742977   -42.437893   -43.56601    -43.67933    -43.86717   ]], shape=(5, 5), dtype=float32)


#### 3. Perkalian

In [15]:
print("Perkalian : ",tf.multiply(random_tensor, prime_tensor))

Perkalian :  tf.Tensor(
[[ -0.8113182    2.9691975    0.19598812  -9.770817     0.49624202]
 [  6.5034676    7.1138754  -27.598083   -10.120562    -0.8440557 ]
 [ 13.514441    -5.8151293   42.702564    13.628201    -9.570897  ]
 [-46.045643    40.376675    -0.83510065  -8.99741     53.648483  ]
 [-71.46207    -18.391504   -24.33843     14.1094475   50.977394  ]], shape=(5, 5), dtype=float32)


#### 4. Pembagian

In [16]:
print("Pembagian : ",tf.divide(random_tensor, prime_tensor))

Pembagian :  tf.Tensor(
[[-8.1131822e-01  7.4229938e-01  2.1776458e-02 -6.1067605e-01
   1.9849680e-02]
 [ 5.3747665e-02  4.9401913e-02 -1.6330227e-01 -5.1635515e-02
  -3.7513587e-03]
 [ 3.0644991e-02 -1.2014731e-02  8.0723181e-02  2.3660071e-02
  -1.5313435e-02]
 [-4.7914300e-02  3.9430346e-02 -7.6685089e-04 -7.7832262e-03
   4.3794680e-02]
 [-4.2511638e-02 -1.0426022e-02 -1.3163024e-02  7.2879377e-03
   2.5174022e-02]], shape=(5, 5), dtype=float32)


#### 5. Pangkat

In [17]:
print("Pangkat : ",tf.pow(random_tensor, prime_tensor))

Pangkat :  tf.Tensor(
[[-8.1131822e-01  2.2040334e+00  2.7882098e-04  3.5602749e+01
   9.6298072e-06]
 [ 3.0851418e-03  1.8840840e-03 -1.7789455e+04  1.0643191e-02
  -1.7955507e-19]
 [ 9.5533214e-05  1.9364561e-13  1.5160045e+06  1.2631500e-06
  -3.7611119e-11]
 [-2.1214481e+05  1.7036416e+03 -0.0000000e+00  2.3426716e-20
   3.1054815e+06]
 [-7.8155469e+09  8.6587212e-16 -2.3519952e-11  1.8472375e-22
   2.7379797e+02]], shape=(5, 5), dtype=float32)


### Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [19]:
print("Nilai MAX baris random tensor : ",tf.argmax(random_tensor, axis = 0).numpy())
print("Nilai MAX kolom random tensor : ",tf.argmax(random_tensor, axis = 1).numpy())

Nilai MAX baris random tensor :  [2 0 2 2 3]
Nilai MAX kolom random tensor :  [1 1 2 4 4]


In [21]:
print("Nilai MIN baris random tensor : ",tf.argmin(random_tensor, axis = 0).numpy())
print("Nilai MIN kolom random tensor : ",tf.argmin(random_tensor, axis = 1).numpy())

Nilai MIN baris random tensor :  [4 4 1 0 2]
Nilai MIN kolom random tensor :  [3 2 4 0 0]


### Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [24]:
print("Penggabungan baris :\n ",tf.concat([random_tensor, prime_tensor],axis = 0).numpy())

Penggabungan baris :
  [[-8.1131822e-01  1.4845988e+00  6.5329373e-02 -2.4427042e+00
   9.9248402e-02]
 [ 5.9122431e-01  5.9282297e-01 -2.1229296e+00 -7.2289723e-01
  -5.6270380e-02]
 [ 6.4354479e-01 -2.6432407e-01  1.8566332e+00  5.6784171e-01
  -3.8283589e-01]
 [-1.4853433e+00  1.2617711e+00 -2.5306080e-02 -2.6462969e-01
   1.5328138e+00]
 [-1.7429771e+00 -4.3789294e-01 -5.6601000e-01  3.2066926e-01
   1.1328310e+00]
 [ 1.0000000e+00  2.0000000e+00  3.0000000e+00  4.0000000e+00
   5.0000000e+00]
 [ 1.1000000e+01  1.2000000e+01  1.3000000e+01  1.4000000e+01
   1.5000000e+01]
 [ 2.1000000e+01  2.2000000e+01  2.3000000e+01  2.4000000e+01
   2.5000000e+01]
 [ 3.1000000e+01  3.2000000e+01  3.3000000e+01  3.4000000e+01
   3.5000000e+01]
 [ 4.1000000e+01  4.2000000e+01  4.3000000e+01  4.4000000e+01
   4.5000000e+01]]


In [25]:
print("Penggabungan kolom :\n ",tf.concat([random_tensor, prime_tensor],axis = 1).numpy())

Penggabungan kolom :
  [[-8.1131822e-01  1.4845988e+00  6.5329373e-02 -2.4427042e+00
   9.9248402e-02  1.0000000e+00  2.0000000e+00  3.0000000e+00
   4.0000000e+00  5.0000000e+00]
 [ 5.9122431e-01  5.9282297e-01 -2.1229296e+00 -7.2289723e-01
  -5.6270380e-02  1.1000000e+01  1.2000000e+01  1.3000000e+01
   1.4000000e+01  1.5000000e+01]
 [ 6.4354479e-01 -2.6432407e-01  1.8566332e+00  5.6784171e-01
  -3.8283589e-01  2.1000000e+01  2.2000000e+01  2.3000000e+01
   2.4000000e+01  2.5000000e+01]
 [-1.4853433e+00  1.2617711e+00 -2.5306080e-02 -2.6462969e-01
   1.5328138e+00  3.1000000e+01  3.2000000e+01  3.3000000e+01
   3.4000000e+01  3.5000000e+01]
 [-1.7429771e+00 -4.3789294e-01 -5.6601000e-01  3.2066926e-01
   1.1328310e+00  4.1000000e+01  4.2000000e+01  4.3000000e+01
   4.4000000e+01  4.5000000e+01]]


### Tampilkan hasil sorting dari kedua variable di atas. (descending)

#### a. Sortting random_tensor

In [35]:
sorting_random = tf.sort(random_tensor, direction="DESCENDING")
sorting_random.numpy()

array([[ 1.4845988 ,  0.0992484 ,  0.06532937, -0.8113182 , -2.4427042 ],
       [ 0.59282297,  0.5912243 , -0.05627038, -0.72289723, -2.1229296 ],
       [ 1.8566332 ,  0.6435448 ,  0.5678417 , -0.26432407, -0.3828359 ],
       [ 1.5328138 ,  1.2617711 , -0.02530608, -0.2646297 , -1.4853433 ],
       [ 1.132831  ,  0.32066926, -0.43789294, -0.56601   , -1.7429771 ]],
      dtype=float32)

#### b. Sortting prime_tensor

In [34]:
sorting_prime= tf.argsort(prime_tensor, direction="DESCENDING")
sorting_prime.numpy()

array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0]])

#### SELESAI